version: '3'
services:
  app:
    tty: true
    image: danlynn/ember-cli:3.0.0
    ports:
      - "${EMBER_SERVE_PORT-8405}:${EMBER_SERVE_PORT-8405}"
      - "${EMBER_LIVER_PORT-8406}:${EMBER_LIVER_PORT-8406}"
      - "${EMBER_TESTS_PORT-8407}:${EMBER_TESTS_PORT-8407}"
    volumes:
      - .:/myapp:cached
      - node_modules:/myapp/node_modules
      - tmp:/myapp/tmp
    restart: on-failure
    entrypoint: "./node_modules/.bin/ember server --port ${EMBER_SERVE_PORT-8405} --live-reload-port ${EMBER_LIVER_PORT-8406} --proxy ${EMBER_GRAPH_PROXY-http://docker.for.mac.host.internal:8400}"
volumes:
  node_modules: {}
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
